config/routes.rb
Rails.application.routes.draw do
  get 'stocks_sold_per_people/new'
  get 'stocks_sold_per_people/index'
  get 'stocks_purchased_per_people/new'
  get 'stocks_purchased_per_people/index'
  get 'download_pdf', to: 'static#download_pdf'
  get '/stocks', to: 'stocks#show'
  get 'transactions/index'
  get 'deposits/index'
  get 'withdraws/index'
  get '/withdraw', to: 'withdraws#new'
  get '/deposit', to: 'deposits#new'
  post '/depositMoney', to:'deposits#create'
  post 'withdrawMoney', to: 'withdraws#create'

  get 'static/welcome_email'

  get '/email', to: 'static#welcome_email'

  get '/buy', to: 'stocks_purchased_per_people#create'
  get '/sell', to: 'stocks_sold_per_people#create'

  get 'stocks/index'

  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'user/new'
  get 'user/show'
  get 'static/about_seth'
  get 'static/home'
  get '/search', to: 'static#home'

  resources :users
  resources :deposits
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  get 			'/login', 		to: 'sessions#new'
  post 		'/login', 		to: 'sessions#create'
  delete 		'/logout', 		to: 'sessions#destroy'

  # get '/search', to: 'deposits#index'
  namespace 'api' do
    namespace 'v1' do
      resources :balances
      get 'stocks/show'
      get 'stocks/company_news'
      get 'stocks/index'
      get 'users/get_stocks_owned_info'
      get 'users/show'
      get 'users/index'
      get 'users/get_balance'
      post 'stocks_purchased_per_people/create'
      post 'stocks_sold_per_people/create'
      get 'stocks_purchased_per_people/index'
      get 'stocks_sold_per_people/index'
      get 'stocks/stock_graph'
      post 'deposits/create'
      post 'withdraws/create'
    end
  end



  root 'static#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :stocks_purchased_per_people
    has_many :stocks_sold_per_people
    validates    :name,  presence:   true, uniqueness:  {case_sensitive:  false}
    validates    :ticker,  presence:   true, uniqueness:  {case_sensitive:  false}

    def self.get(ticker)
      Finnhub::GetQuoteService.call(ticker.upcase(), false)
      Stock.find_by(ticker: ticker)
    end

    def self.get_stocks_owned(ticker, user_id)
      Stock.joins(:stocks_purchased_per_people).where(' "user_id" = ? and "ticker" = ?', user_id, ticker ).pluck(:quantity).sum() - Stock.joins(:stocks_sold_per_people).where(' "user_id" = ? and "ticker" = ?', user_id, ticker ).pluck(:quantity).sum()
    end

    def self.get_last_update(ticker)
      stock = Stock.select('updated_at').find_by(ticker: ticker)
      if stock
        return stock[:updated_at]
      end
      nil
    end

    def self.get_most_recent_price(ticker)
      Stock.find_by(ticker: ticker)[:most_recent_price]
    end

    def self.get_most_recent_quote(ticker)
      stock = Stock.find_by(ticker: ticker)
      {MOST_RECENT_PRICE => stock[:most_recent_price], DAY_CHANGE => stock[:day_change],
        DAY_PERCENT_CHANGE => stock[:day_percent_change], DAY_HIGH_PRICE => stock[:day_high_price],
        DAY_LOW_PRICE => stock[:day_low_price], DAY_OPEN_PRICE => stock[:day_open_price],
        DAY_PREVIOUS_CLOSE_PRICE => stock[:day_previous_close_price]}
    end

    def self.update_price(ticker, new_price)
      Stock.find_by(ticker: ticker).update(most_recent_price: new_price)
    end

    def self.update_quote(ticker, new_quote)
      Stock.find_by(ticker: ticker).update(most_recent_price: new_quote[MOST_RECENT_PRICE],
        day_change: new_quote[DAY_CHANGE], day_percent_change: new_quote[DAY_PERCENT_CHANGE],
        day_high_price: new_quote[DAY_HIGH_PRICE], day_low_price: new_quote[DAY_LOW_PRICE],
        day_open_price: new_quote[DAY_OPEN_PRICE], day_previous_close_price: new_quote[DAY_PREVIOUS_CLOSE_PRICE])
    end

end

app/controllers/api/v1/stocks_controller.rb
module Api
  module V1
    class StocksController < ApplicationController
      def show
        search =  params[:ticker]
        stock = Stock.get(search)
        render json: stock, status: :ok
      end
      def index
        stocks = Stock.all
        render json: stocks, status: :ok
      end

      def stock_graph
        data = StocksController.helpers.get_stock_history(params[:ticker], params[:days])
        info = {"min" => data[2], "max" => data[1], "new_graph" => data[0]}
        render json: info , status: :ok
      end

      def company_news
        news = Finnhub::GetCompanyNewsService.call(params[:ticker])
        render json: news, status: :ok
      end
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include StocksHelper
  TEN_PERCENT = 0.1

  before_action :create_model, only: [:show]

  def show()
    @ticker = params[:ticker].upcase()
    @quote = Finnhub::GetQuoteService.call(@ticker, false)

    @days = params.has_key?(:days) ? params[:days] : 30
    graph_max_min = get_stock_history(@ticker, @days)
    @new_graph = graph_max_min[0]
    @max = (graph_max_min[1] + graph_max_min[1] * TEN_PERCENT).round()
    @min = (graph_max_min[2] - graph_max_min[2] * TEN_PERCENT).round()
    @company_profile = Finnhub::GetCompanyProfileService.call(@ticker)
  end

  def create()
    new_quote = Finnhub::GetQuoteService.call(params[:ticker], true)
    @stock = Stock.new(ticker: params[:ticker].upcase(), name: Finnhub::GetCompanyProfileService.call(params[:ticker])[:name],
    most_recent_price: new_quote[MOST_RECENT_PRICE], day_change: new_quote[DAY_CHANGE], day_percent_change: new_quote[DAY_PERCENT_CHANGE],
    day_high_price: new_quote[DAY_HIGH_PRICE], day_low_price: new_quote[DAY_LOW_PRICE], day_open_price: new_quote[DAY_OPEN_PRICE],
    day_previous_close_price: new_quote[DAY_PREVIOUS_CLOSE_PRICE])
    if @stock.save
       flash[:success] = 'Stock Created Successfully'
    else
      flash[:danger] = 'Stock Does Not Exist'
      redirect_to root_path
    end
  end

  def index()
    @stocks = Stock.all()
  end

  private

  def create_model()
    unless(stock_exist?())
      create()
    end
  end

  def stock_exist?()
    return Stock.exists?(ticker: params[:ticker].upcase())
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
  require 'finnhub_ruby'
  require 'date'

  SECONDS_IN_DAYS = 86400


  def get_stock_history(ticker, days)
    if(days == '1' or days == '3' or days == '7')
      interval = '30'
    else
      interval = 'D'
    end
    days = days.to_i()
    today = Date.today
    while(today.on_weekend?())
     today = today.prev_day()
    end
    today = today.to_time().to_i()
    start_day = today - days * SECONDS_IN_DAYS

    get_new_graph_max_min(ticker, interval, start_day, today)

  end

  private

    def get_new_graph_max_min(ticker, interval, start_day, today)
      history = Finnhub::GetStockCandlesService.call(ticker, interval, start_day, today).to_hash

      new_graph = {}
      i = 0
      max = -1
      min = 1_000_000_000

      while i < history[:c].count()
        max =  history[:c][i] > max ? history[:c][i] : max
        min = history[:c][i] < min ? history[:c][i] : min
        time = Time.at(history[:t][i]).to_datetime()
        new_graph[time] = history[:c][i]
        i += 1
      end

      [new_graph, max, min]
    end

end

app/views/stocks/index.html.erb
<%@stocks.each do |s|%>
  <h1><%= s.name%></h1>
<%end%>

app/views/stocks/show.html.erb
<% provide(:title, 'Stock')%>
<div class="container">
  <div class="row justify-content-start">
    <div class="col-1">
      <%=image_tag @company_profile[:logo], alt: "Logo", height: "100px", width: "100px", class: 'rounded mt-5' %>
    </div>
    <div class="col">
      <h1 class="display-3 mt-5"><%=@company_profile[:name]%></h1>
    </div>
  </div>

  <div class="row justify-content-start mt-4">
    <div class="col">
      <b><h1 class="display-6 text-info">Price: <%='%.2f' % @quote[:c]%></h1></b>
    </div>
    <div class="col">
      <h1 class="display-6">High: <%='%.2f' % @quote[:h]%></h1>
    </div>
    <div class="col">
      <h1 class="display-6">Low: <%= '%.2f' % @quote[:l]%></h1>
    </div>
    <div class="col">
      <h1 class="display-6">Open: <%='%.2f' % @quote[:o]%></h1>
    </div>
  </div>

  <% if logged_in?()%>
  <div class="row">
    <div class="btn-group m-5">
      <%=link_to 'BUY', stocks_purchased_per_people_new_path(:ticker => @company_profile[:ticker]), class: 'btn btn-success btn-lg m-2'%>
      <%=link_to 'SELL', stocks_sold_per_people_new_path(:ticker => @company_profile[:ticker]), class: 'btn btn-danger btn-lg m-2'%>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-6">
      <div class="d-flex align-items-center">
        <%= link_to '1 day', stocks_path(:ticker => @ticker, :days => '1'), class: 'btn btn-primary mx-1'%>
        <%= link_to '3 days', stocks_path(:ticker => @ticker, :days => '3'), class: 'btn btn-primary mx-1'%>
        <%= link_to '1 week', stocks_path(:ticker => @ticker, :days => '7'), class: 'btn btn-primary mx-1'%>
        <%= link_to '1 month', stocks_path(:ticker => @ticker, :days => '30'), class: 'btn btn-primary mx-1'%>
        <%= link_to '3 months', stocks_path(:ticker => @ticker, :days => '90'), class: 'btn btn-primary mx-1'%>
        <%= link_to '6 month', stocks_path(:ticker => @ticker, :days => '180'), class: 'btn btn-primary mx-1'%>
        <%= link_to '1 year', stocks_path(:ticker => @ticker, :days => '365'), class: 'btn btn-primary mx-1'%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <%if @days.to_i <= 7%>
      <%=  line_chart(@new_graph, width: "1000px", height: "500px", min: @min, max: @max, stepSize: 1, points: false, curve: false, discrete: true) %>
      <%else%>
      <%=  line_chart(@new_graph, width: "1000px", height: "500px", min: @min, max: @max, points: false, curve: false) %>
      <%end%>
    </div>
  </div>

</div>