config/routes.rb
Rails.application.routes.draw do
  get 'stocks_sold_per_people/new'
  get 'stocks_sold_per_people/index'
  get 'stocks_purchased_per_people/new'
  get 'stocks_purchased_per_people/index'
  get 'download_pdf', to: 'static#download_pdf'
  get '/stocks', to: 'stocks#show'
  get 'transactions/index'
  get 'deposits/index'
  get 'withdraws/index'
  get '/withdraw', to: 'withdraws#new'
  get '/deposit', to: 'deposits#new'
  post '/depositMoney', to:'deposits#create'
  post 'withdrawMoney', to: 'withdraws#create'

  get 'static/welcome_email'

  get '/email', to: 'static#welcome_email'

  get '/buy', to: 'stocks_purchased_per_people#create'
  get '/sell', to: 'stocks_sold_per_people#create'

  get 'stocks/index'

  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'user/new'
  get 'user/show'
  get 'static/about_seth'
  get 'static/home'
  get '/search', to: 'static#home'

  resources :users
  resources :deposits
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  get 			'/login', 		to: 'sessions#new'
  post 		'/login', 		to: 'sessions#create'
  delete 		'/logout', 		to: 'sessions#destroy'

  # get '/search', to: 'deposits#index'
  namespace 'api' do
    namespace 'v1' do
      resources :balances
      get 'stocks/show'
      get 'stocks/company_news'
      get 'stocks/index'
      get 'users/get_stocks_owned_info'
      get 'users/show'
      get 'users/index'
      get 'users/get_balance'
      post 'stocks_purchased_per_people/create'
      post 'stocks_sold_per_people/create'
      get 'stocks_purchased_per_people/index'
      get 'stocks_sold_per_people/index'
      get 'stocks/stock_graph'
      post 'deposits/create'
      post 'withdraws/create'
    end
  end



  root 'static#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<br><br><br>
<hr>
<div class="container">


  <div class="row w-25 mx-auto my-3">
    <div class="col">
      <button type="button" class="btn btn-outline-primary" onclick="location.href='https://www.facebook.com/seth.fagen'">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </svg>
      <span class="visually-hidden">Button</span>
      </button>
    </div>

    <div class="col">
      <button type="button" class="btn btn-outline-primary" onclick="location.href='https://www.linkedin.com/in/seth-fagen-614648162/'">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
          <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"></path>
        </svg>
      <span class="visually-hidden">Button</span>
      </button>
    </div>


    <div class="col">
      <button type="button" class="btn btn-outline-primary" onclick="location.href='https://github.com/seth174'">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
        </svg>
      <span class="visually-hidden">Button</span>
      </button>
    </div>

    <div class="col">
      <button type="button" class="btn btn-outline-primary" onclick="location.href='https://www.instagram.com/seth174/'">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
        </svg>
      <span class="visually-hidden">Button</span>
      </button>
    </div>

  </div>

  <div class="row">
    <div class="col">
      <%= form_with url: "/email", class: 'text-center', method: :get do |form| %>
        <div class="d-flex justify-content-center">
          <div class="pe-2 bd-highlight align-self-center"><%= form.label :email, "Enter email to receive my email", class: 'form-text form-text-sm' %></div>
          <div class="pe-2 bd-highlight align-self-center"><%= form.text_field :email, class: 'form-control form-control-sm', placeholder: 'Email'%></div>
          <div class="bd-highlight align-self-center"><%= form.submit "submit", class: 'btn btn-primary btn-sm' %></div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row text-center my-3">
    <div class="col">
      <% if logged_in? %>
        <%=button_to 'log out', logout_path, method: :delete, class: 'btn btn-primary btn-sm', data: {:confirm => 'Are you sure?'} %>
      <% end %>
    </div>

  </div>



</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%=link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About Seth', static_about_seth_path, class: 'nav-link' %>
      </li>
      <li><%= link_to "Sign up", '/signup', class: 'nav-link' %></li>
      <%if logged_in?%>
        <li><%= link_to "Edit Account", edit_user_path(current_user), class: 'nav-link' %></li>
        <li><%= link_to "All Users", users_path, class: 'nav-link' %></li>
        <li><%= link_to "deposit", '/deposit', class: 'nav-link' %></li>
        <li><%= link_to "withdraw", '/withdraw', class: 'nav-link' %></li>
        <li><%= link_to "transactions", transactions_index_path, id: current_user.id, class: 'nav-link' %></li>
        <li><%= link_to "All Deposits", deposits_index_path, class: 'nav-link' %></li>
        <li><%= link_to "All Withdraws", withdraws_index_path, class: 'nav-link' %></li>
      <%end%>
    </ul>
  </div>
</nav>


<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto mb-lg-0">
      <li>
      <div class="d-flex flex-row bd-highlight">
        <div class="p-2 bd-highlight align-self-center">

          <%= image_tag "home_image.jpg", alt: "logo", height:"100", width: "220", class: "d-inline-block align-text-top", id: 'home_image' %>
        </div>
        <div class="pe-2 bd-highlight align-self-center">
          <h1><%= link_to "Seth's Trading App", root_path, class: 'nav-link align-text-top' %></h1>
        </div>
      </div>
      </li>
    </ul>
    <ul class="navbar-nav mx-auto">
      <li>
      <%= form_with url: "/stocks", method: :get do |form| %>
        <div class="d-flex flex-row bd-highlight">
          <div class="p-2 bd-highlight align-self-center"><%= form.label :ticker, "Search Stock Ticker:", class: 'col-form-label col-form-label-lg' %></div>
          <div class="p-2 bd-highlight align-self-center"><%= form.text_field :ticker, class: 'form-control-lg'%></div>
          <div class="p-2 bd-highlight align-self-center"><%= form.submit "Search", class: 'btn btn-warning btn-lg' %></div>
        </div>
      <% end %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto mb-lg-0 p-2">
      <%=link_to 'Login', '/login', class: 'btn btn-lg btn-danger' %>
    </ul>
  </div>
</nav>

app/views/layouts/_header_login.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'About Seth', static_about_seth_path, class: 'nav-link' %>
      </li>
      <li><%= link_to "Overview", current_user, class: 'nav-link' %></li>
      <li><%= link_to "Edit Account", edit_user_path(current_user), class: 'nav-link' %></li>
      <li><%= link_to "All Users", users_path, class: 'nav-link' %></li>
      <li><%= link_to "stocks", stocks_index_path, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <%= link_to "Seth's Trading", root_path, class: "navbar-brand mx-2" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item dropdown">
        <%= link_to "Account Overview", current_user, class: 'nav-link'%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Deposit/Withdraw
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Deposit", "/deposit", class: 'dropdown-item'%>
          <%= link_to "New Withdraw", "/withdraw", class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to "Deposit History", deposits_index_path, class: 'dropdown-item'%>
          <%= link_to "Withdraw History", withdraws_index_path, class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to "Transaction History", transactions_index_path, class: 'dropdown-item'%>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Buy/Sell Stocks
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Stocks Bought", stocks_purchased_per_people_index_path, class: 'dropdown-item'%>
          <%= link_to "Buy Stock", stocks_purchased_per_people_new_path, class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to "Stocks Sold", stocks_sold_per_people_index_path, class: 'dropdown-item'%>
          <%= link_to "Sell Stock", stocks_sold_per_people_new_path, class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to "Transaction History", transactions_index_path, class: 'dropdown-item'%>
        </div>
      </li>

    </ul>
    <%= form_with url: "/stocks", method: :get do |form| %>
      <div class="d-flex flex-row bd-highlight">
        <div class="p-2 bd-highlight align-self-center"><%= form.label :ticker, "Search Stock:" %></div>
        <div class="p-2 bd-highlight align-self-center"><%= form.text_field :ticker, class: 'form-control'%></div>
        <div class="p-2 bd-highlight align-self-center"><%= form.submit "Search", class: 'btn btn-warning btn' %></div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if logged_in?%>
      <%= render 'layouts/header_login'%>
    <% else %>
      <%= render 'layouts/header'%>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>